### 角色列表
GET http://127.0.0.1:8000/admin/sys/role/list
Authorization: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwic3lzdGVtVHlwZSI6MSwiaWF0IjoxNzE1MjM2NzI3LCJleHAiOjE3MTUyNzk5Mjd9.tCPHIp-OmgIjtk1I8SgWNsVoy01FlMzVFkfnh4Ez3V88sEAik4biUa4S5_zj2G3s


### 根据角色id查询角色信息及 所有的菜单和权限
GET http://127.0.0.1:8000/admin/sys/role/info?roleId=1
Authorization: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcxNTAxNzgyMywiZXhwIjoxNzE1MDYxMDIzfQ.zreHrWlFAWkhFYVOv5lXzoZTnoxTvYItasZDdQPVfTazTqNhPEHkzmAk6PzB4klf


### 保存角色及权限
POST http://127.0.0.1:8000/admin/sys/role/save
Authorization: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcxNTAxNzgyMywiZXhwIjoxNzE1MDYxMDIzfQ.zreHrWlFAWkhFYVOv5lXzoZTnoxTvYItasZDdQPVfTazTqNhPEHkzmAk6PzB4klf
Content-Type: application/json

{
  "roleId": 2,
  "roleName": "客服",
  "remark": "客服",
  "menuIdList": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10
  ],
  "permissionIdList": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10
  ]
}


### 获取所有角色id和名称
GET http://127.0.0.1:8000/admin/sys/role/listAll
Authorization: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcxNTAxNzgyMywiZXhwIjoxNzE1MDYxMDIzfQ.zreHrWlFAWkhFYVOv5lXzoZTnoxTvYItasZDdQPVfTazTqNhPEHkzmAk6PzB4klf


