### 系统配置列表
GET http://localhost:8000/admin/sys/config/listAll
Authorization: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwic3lzdGVtVHlwZSI6MSwiaWF0IjoxNzE1MjM2NzI3LCJleHAiOjE3MTUyNzk5Mjd9.tCPHIp-OmgIjtk1I8SgWNsVoy01FlMzVFkfnh4Ez3V88sEAik4biUa4S5_zj2G3s